### ISSUE TITLE
no html output

### ISSUE THREAD

**Issue by drezden-cell** [WebBreacher/untappdScraper#10]
I have created only bing api key, but didn't get any html output, how does it work? help, please

**Comment by WebBreacher** [comment]
Hey there. I've checked the code and, I'm sorry, but I removed the BING API Geocoding a while ago and never updated the README file. I've updated it and some other parts of the script so now it only uses Google's Geocoding API.

It is possible that we may be able to use the geopy library to geocode addresses to lat/long but, after just trying it, it is not nearly as good as Google. It misses a lot of the locations. Upside is it is free.

I do not have time now to rewrite the script to add in the geopy content. So, for now, the script will stay a Google API-only geocoding app.
