### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by wbulmer** [WebBreacher/untappdScraper#6]

**Comment by WebBreacher** [comment]
thanks for trying the script!

couple things:

1. you should not have to edit the python code for the script to work. I suggest reverting it back to the original state
1. you need python 3.x to run the script. not python2. run "python --version" in your command line and see what comes back. you can also try running "python3 --version". if you don't have python, go install it then....
1. to run the script, enter this on the command line: python untappd.py -u nvrhapy (change nvrhapy user name to your friend's)

**Comment by wbulmer** [comment]
HI Micah

Ok I got it to run I think, see attached.  But it appears it stops after 91 beers, he has over 2000 listed?

https://untappd.com/user/Jim11914 

Regards Warren

Sent from Mail for Windows 10

**Comment by WebBreacher** [comment]
I dont see the attached output. can you repost?

also, maybe try it against another user account like nvrhapy

**Comment by wbulmer** [comment]
Sorry

Here it is.

Microsoft Windows [Version 10.0.17134.191]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Warren Bulmer>python untapped.py -u Jim11914

[ ] USER DATA: Requesting https://untappd.com/user/Jim11914
        Total Beers:       92
Traceback (most recent call last):
  File "untapped.py", line 109, in <module>
    print '        Total Unique:  {:>6}'.format(user[1])
IndexError: list index out of range

C:\Users\Warren Bulmer>

Unfortunately Nvrhappy no longer has a public profile...

https://untappd.com/user/nvrhappy 

Regards Warren

Sent from Mail for Windows 10

**Comment by WebBreacher** [comment]
It worked for me. 

![2018-08-10_16-39-17](https://user-images.githubusercontent.com/2359093/43985404-1a5cc54e-9cbc-11e8-91ae-7f8a761e9079.png)
